### ISSUE TITLE
lots of NPE in BitBucket logs

### ISSUE THREAD

**Issue by wemu** [TrimbleSolutionsCorporation/TeamcityTriggerHook#13]
Hallo

I've looked into the atlassian-bitbucket.log and noticed quite a lot of NullPointerExceptions that seem to come from the plugin - although we currently only test it on a handful of builds:

we use RC8

`
2017-03-07 08:37:08,748 ERROR [http-nio-8443-exec-149] U803943 @1JI9HPHx517x20993387x9 1bkmsyw 10.36.101.84 "GET /rest/teamcity/latest/projects/..../externalbuilds HTTP/1.1" c.a.p.r.c.e.j.ThrowableExceptionMapper Uncaught exception thrown by REST service: null
java.lang.NullPointerException: null
	at com.trimble.tekla.rest.TeamctiyRest.getExternalConfiguration(TeamctiyRest.java:253) ~[plugin_2576699521728206614_TeamcityTriggerHook-3.0.0-RC8_1488295490000.jar:na]
	at com.atlassian.applinks.core.rest.context.ContextFilter.doFilter(ContextFilter.java:24) [applinks-plugin-5.2.2_1471837580000.jar:na]
	at com.atlassian.applinks.core.rest.context.ContextFilter.doFilter(ContextFilter.java:24) [applinks-plugin-5.2.2_1471837580000.jar:na]
	at com.atlassian.applinks.core.rest.context.ContextFilter.doFilter(ContextFilter.java:24) [applinks-plugin-5.2.2_1471837580000.jar:na]
	at com.atlassian.applinks.core.rest.context.ContextFilter.doFilter(ContextFilter.java:24) [applinks-plugin-5.2.2_1471837580000.jar:na]
	at com.atlassian.applinks.core.rest.context.ContextFilter.doFilter(ContextFilter.java:24) [applinks-plugin-5.2.2_1471837580000.jar:na]
	at com.atlassian.plugin.connect.plugin.auth.scope.ApiScopingFilter.doFilter(ApiScopingFilter.java:81) [atlassian-connect-plugin-1.1.86-bitbucket-04.jar:na]
	at com.atlassian.stash.internal.spring.security.StashAuthenticationFilter.doFilter(StashAuthenticationFilter.java:88) [classes/:na]
	at com.atlassian.stash.internal.web.auth.BeforeLoginPluginAuthenticationFilter.doInsideSpringSecurityChain(BeforeLoginPluginAuthenticationFilter.java:109) [classes/:na]
	at com.atlassian.stash.internal.web.auth.BeforeLoginPluginAuthenticationFilter.doFilter(BeforeLoginPluginAuthenticationFilter.java:75) [classes/:na]
	at com.atlassian.security.auth.trustedapps.filter.TrustedApplicationsFilter.doFilter(TrustedApplicationsFilter.java:94) [atlassian-trusted-apps-core-4.2.0.jar:na]
	at com.atlassian.oauth.serviceprovider.internal.servlet.OAuthFilter.doFilter(OAuthFilter.java:67) [atlassian-oauth-service-provider-plugin-2.0.3_1471837580000.jar:na]
	at com.atlassian.core.filters.ServletContextThreadLocalFilter.doFilter(ServletContextThreadLocalFilter.java:21) [atlassian-core-4.6.19.jar:na]
	at com.atlassian.core.filters.AbstractHttpFilter.doFilter(AbstractHttpFilter.java:31) [atlassian-core-4.6.19.jar:na]
	at com.atlassian.plugin.connect.plugin.auth.user.ThreeLeggedAuthFilter.doFilter(ThreeLeggedAuthFilter.java:109) [atlassian-connect-plugin-1.1.86-bitbucket-04.jar:na]
	at com.atlassian.jwt.internal.servlet.JwtAuthFilter.doFilter(JwtAuthFilter.java:32) [jwt-plugin-1.5.11-0002_1471837580000.jar:na]
	at com.atlassian.stash.internal.web.auth.BeforeLoginPluginAuthenticationFilter.doBeforeBeforeLoginFilters(BeforeLoginPluginAuthenticationFilter.java:87) [classes/:na]
	at com.atlassian.stash.internal.web.auth.BeforeLoginPluginAuthenticationFilter.doFilter(BeforeLoginPluginAuthenticationFilter.java:73) [classes/:na]
	at com.atlassian.stash.internal.request.DefaultRequestManager.doAsRequest(DefaultRequestManager.java:86) ~[bitbucket-service-impl-4.8.5.jar:na]
	at com.atlassian.stash.internal.hazelcast.ConfigurableWebFilter.doFilter(ConfigurableWebFilter.java:38) ~[classes/:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_66]
	at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_66]
	... 226 frames trimmed
`

then there is a less frequent one:

`
2017-03-07 08:38:02,234 ERROR [http-nio-8443-exec-90] U112334 @1JI9HPHx518x20994664x10 grhs6f 10.38.68.207 "GET /projects/VVL/repos/..../pull-requests/43/overview HTTP/1.1" c.a.p.web.DefaultWebInterfaceManager Could not evaluate condition 'com.atlassian.plugin.web.conditions.AndCompositeCondition@352e3bff' for descriptor: com.trimble.tekla:stash.teamcity.trigger (null)
java.lang.NullPointerException: null
	at com.trimble.tekla.WebhookIsEnabledCondition.shouldDisplay(WebhookIsEnabledCondition.java:67) ~[na:na]
`

and also:

`
2017-03-07 08:38:04,362 ERROR [http-nio-8443-exec-141] U112334 @1JI9HPHx518x20994726x4 grhs6f 10.38.68.207 "GET /rest/teamcity/latest/projects/VVL/repos/.../builds HTTP/1.1" c.a.p.r.c.e.j.ThrowableExceptionMapper Uncaught exception thrown by REST service: null
java.lang.NullPointerException: null
	at com.trimble.tekla.rest.TeamctiyRest.getBuildsConfiguration(TeamctiyRest.java:198) ~[plugin_2576699521728206614_TeamcityTriggerHook-3.0.0-RC8_1488295490000.jar:na]
	at com.atlassian.applinks.core.rest.context.ContextFilter.doFilter(ContextFilter.java:24) [applinks-plugin-5.2.2_1471837580000.jar:na]
	at com.atlassian.applinks.core.rest.context.ContextFilter.doFilter(ContextFilter.java:24) [applinks-plugin-5.2.2_1471837580000.jar:na]
	at com.atlassian.applinks.core.rest.context.ContextFilter.doFilter(ContextFilter.java:24) [applinks-plugin-5.2.2_1471837580000.jar:na]
	at com.atlassian.applinks.core.rest.context.ContextFilter.doFilter(ContextFilter.java:24) [applinks-plugin-5.2.2_1471837580000.jar:na]
	at com.atlassian.applinks.core.rest.context.ContextFilter.doFilter(ContextFilter.java:24) [applinks-plugin-5.2.2_1471837580000.jar:na]
	at com.atlassian.plugin.connect.plugin.auth.scope.ApiScopingFilter.doFilter(ApiScopingFilter.java:81) [atlassian-connect-plugin-1.1.86-bitbucket-04.jar:na]
	at com.atlassian.stash.internal.spring.security.StashAuthenticationFilter.doFilter(StashAuthenticationFilter.java:88) [classes/:na]
`

and some more:

`
Caused by: java.lang.NullPointerException: null
	at com.trimble.tekla.TeamcityPullrequestEventListener.TriggerBuildFromPullRequest(TeamcityPullrequestEventListener.java:77) ~[na:na]
	at com.trimble.tekla.TeamcityPullrequestEventListener.onPullRequestOpenedEvent(TeamcityPullrequestEventListener.java:39) ~[na:na]
	at com.atlassian.event.internal.SingleParameterMethodListenerInvoker.invoke(SingleParameterMethodListenerInvoker.java:36) ~[atlassian-event-3.0.0.jar:na]
	... 6 common frames omitted
`

The Trigger Hook is not enabled on those repositories that throw the NPE.

Could you please have a look?

**Comment by jmecosta** [comment]
can you try the official 3.0.0 ive solved some npe there

**Comment by wemu** [comment]
Hallo

I've upgraded to 3.0 from the atlassian marketplace. Some NPEs are still present:

`
2017-03-09 06:26:22,303 ERROR [http-nio-8443-exec-1] username @1UTEYXHx386x2768171x6 dvoanr 172.16.105.71 "GET /projects/BE/repos/b2e-rwc/pull-requests/2102/overview HTTP/1.1" c.a.p.web.DefaultWebInterfaceManager Could not evaluate condition 'com.atlassian.plugin.web.conditions.AndCompositeCondition@4e2566ef' for descriptor: com.trimble.tekla:stash.teamcity.trigger (null)
java.lang.NullPointerException: null
	at com.trimble.tekla.WebhookIsEnabledCondition.shouldDisplay(WebhookIsEnabledCondition.java:67) ~[na:na]
	at com.atlassian.plugin.web.conditions.AndCompositeCondition.shouldDisplay(AndCompositeCondition.java:14) ~[atlassian-plugins-webfragment-api-4.1.0.jar:na]
`

or:
`
2017-03-09 06:26:24,380 ERROR [http-nio-8443-exec-12] username @1UTEYXHx386x2768287x9 dvoanr 172.16.105.71 "GET /rest/teamcity/latest/projects/BE/repos/b2e-rwc/externalbuilds HTTP/1.1" c.a.p.r.c.e.j.ThrowableExceptionMapper Uncaught exception thrown by REST service: null
java.lang.NullPointerException: null
	at com.trimble.tekla.rest.TeamctiyRest.getExternalConfiguration(TeamctiyRest.java:253) ~[plugin_7108341048333861963_TeamcityTriggerHook-3.0.0_1488964701000.jar:na]
	at com.atlassian.applinks.core.rest.context.ContextFilter.doFilter(ContextFilter.java:24) [applinks-plugin-5.2.2_1471837580000.jar:na]
`

or

`
2017-03-09 06:26:24,390 ERROR [http-nio-8443-exec-84] username @1UTEYXHx386x2768286x8 dvoanr 172.16.105.71 "GET /rest/teamcity/latest/projects/BE/repos/b2e-rwc/builds HTTP/1.1" c.a.p.r.c.e.j.ThrowableExceptionMapper Uncaught exception thrown by REST service: null
java.lang.NullPointerException: null
	at com.trimble.tekla.rest.TeamctiyRest.getBuildsConfiguration(TeamctiyRest.java:198) ~[plugin_7108341048333861963_TeamcityTriggerHook-3.0.0_1488964701000.jar:na]
	at com.atlassian.applinks.core.rest.context.ContextFilter.doFilter(ContextFilter.java:24) [applinks-plugin-5.2.2_1471837580000.jar:na]
`

these are the most common ones - if there is another one its currently well hidden behind those

**Comment by jmecosta** [comment]
OK I will check our logs also. And provide a fix for it

**Comment by jmecosta** [comment]
@wemu i dont anymore see any npe in our logs. ive pubilshed 3.0.2. please check if all is good

**Comment by wemu** [comment]
cool :-)
I'll have a look
