### ISSUE TITLE
No support for BitBucket 5

### ISSUE THREAD

**Issue by spacecoder007** [TrimbleSolutionsCorporation/TeamcityTriggerHook#18]
Method was removed in v5.

https://developer.atlassian.com/static/javadoc/bitbucket-server/4.6.2/api/reference/com/atlassian/bitbucket/repository/RefChange.html

https://developer.atlassian.com/static/javadoc/bitbucket-server/5.0.1/api/reference/com/atlassian/bitbucket/repository/RefChange.html

`java.lang.RuntimeException: com.atlassian.bitbucket.repository.RefChange.getRefId()Ljava/lang/String;. Listener: com.atlassian.stash.internal.hook.repository.CoreRefChangeEventToRepositoryHookAdapter event: com.atlassian.bitbucket.event.repository.RepositoryPushEvent
	at com.atlassian.event.internal.SingleParameterMethodListenerInvoker.invoke(SingleParameterMethodListenerInvoker.java:55)
	at com.atlassian.stash.internal.event.AsyncBatchingInvokersTransformer$AsyncInvokerBatch.invoke(AsyncBatchingInvokersTransformer.java:109)
	at com.atlassian.event.internal.AsynchronousAbleEventDispatcher$1$1.run(AsynchronousAbleEventDispatcher.java:38)
	at com.atlassian.sal.core.executor.ThreadLocalDelegateRunnable.run(ThreadLocalDelegateRunnable.java:34)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.lang.Thread.run(Thread.java:745)
	... 1 frame trimmed
Caused by: java.lang.NoSuchMethodError: com.atlassian.bitbucket.repository.RefChange.getRefId()Ljava/lang/String;
	at com.trimble.tekla.TeamcityTriggerHook.postReceive(TeamcityTriggerHook.java:69)
	at com.atlassian.stash.internal.plugin.legacy.AsyncPostReceiveRepositoryHookAdapter.postUpdate(AsyncPostReceiveRepositoryHookAdapter.java:22)
	at com.atlassian.stash.internal.plugin.legacy.CompositeRepositoryHook.lambda$postUpdate$1(CompositeRepositoryHook.java:58)
	at com.atlassian.stash.internal.plugin.legacy.CompositeRepositoryHook$$Lambda$1153/1427667203.apply(Unknown Source)
	at com.atlassian.stash.internal.plugin.legacy.CompositeRepositoryHook.handlingExceptions(CompositeRepositoryHook.java:86)
	at com.atlassian.stash.internal.plugin.legacy.CompositeRepositoryHook.postUpdate(CompositeRepositoryHook.java:57)
	at com.atlassian.stash.internal.hook.repository.DefaultRepositoryHookService.postUpdate(DefaultRepositoryHookService.java:573)
	at com.atlassian.stash.internal.hook.repository.DefaultRepositoryHookService.doPostUpdate(DefaultRepositoryHookService.java:417)
	at com.atlassian.stash.internal.hook.repository.DefaultRepositoryHookService.postUpdate(DefaultRepositoryHookService.java:235)
	at com.atlassian.stash.internal.hook.repository.CoreRefChangeEventToRepositoryHookAdapter.onRefsChanged(CoreRefChangeEventToRepositoryHookAdapter.java:49)
	at com.atlassian.event.internal.SingleParameterMethodListenerInvoker.invoke(SingleParameterMethodListenerInvoker.java:40)
	... 6 common frames omitted`

**Comment by jmecosta** [comment]
thanks for reporting this, when reading the release notes i havent notice any api braking changes. i have now updated the release in marketplace to refer the incompatibility

**Comment by jmecosta** [comment]
3.0.4 in update center should fix this. thanks
