### ISSUE TITLE
Push new branch to bitbucket does not trigger a build

### ISSUE THREAD

**Issue by dzwicker** [TrimbleSolutionsCorporation/TeamcityTriggerHook#43]
If a branch is created locally and pushed to bitbucket it seams not to trigger teamcity. Even with some local commits and pushing to server no trigger fires.

If i do a 'ammend commit' after pushing the new branch (and push this new ammended commit) teamcity starts a new build

**Comment by jmecosta** [comment]
Can you export your configuration?

**Comment by dzwicker** [comment]
```
{
    "8b8efe5b-50c6-XXXX-a01a-8050230de4f8": {
        "regex": "refs/heads/(.*)",
        "target": "XXXXX",
        "type": "vcs",
        "triggerOnEmptyBranches": true,
        "triggerOnPullRequest": false,
        "cancelRunningBuilds": false,
        "triggerInclusion": "",
        "triggerExclusion": "",
        "downStreamTriggerType": "build",
        "downStreamTriggerTarget": ""
    }
}
```

**Comment by dzwicker** [comment]
please see https://github.com/TrimbleSolutionsCorporation/TeamcityTriggerHook/issues/44

**Comment by jmecosta** [comment]
i can see that you use "type": "vcs", this means you are just telling Teamcity to check for changes. So teamcity might or not build your branch depending on the type of configuration there.

if you want more control over the all thing, i suggest you to use trigger type = buildtype and trigger directly the build configurations. that should work better since the hook has more control over the all thing

**Comment by jmecosta** [comment]
Is the trigger on empty branch option enabled?

**Comment by dzwicker** [comment]
trigger for empty branches is enabled, yes

**Comment by dzwicker** [comment]
Can see this stacktrace in bitbucket:
```
2019-01-08 16:44:50,248 WARN  [AtlassianEvent::thread-4] crinjes @1PJIQIEx1004x1831598x1 1oy0hfl 172.16.192.78,127.0.0.1 "POST /rest/branch-utils/latest/projects/DEVB/repos/sp-connector-customers/branches HTTP/1.1" c.a.s.i.h.r.DefaultRepositoryHookService [DEVB/sp-connector-customers[142]] Error calling TeamcityTriggerHook.postUpdate
com.atlassian.bitbucket.commit.NoSuchCommitException: Commit '0000000000000000000000000000000000000000' does not exist in repository 'SP Connector Customers'.
	at com.atlassian.bitbucket.scm.git.command.GitCommandExitHandler.newNoSuchCommitException(GitCommandExitHandler.java:174)
	at com.atlassian.bitbucket.scm.git.command.GitCommandExitHandler.evaluateStdErr(GitCommandExitHandler.java:77)
	at com.atlassian.bitbucket.scm.git.command.GitCommandExitHandler.onError(GitCommandExitHandler.java:204)
	at com.atlassian.bitbucket.scm.DefaultCommandExitHandler.onExit(DefaultCommandExitHandler.java:32)
	at com.atlassian.bitbucket.scm.BaseCommand.callExitHandler(BaseCommand.java:153)
	at com.atlassian.bitbucket.scm.BaseCommand$CommandFuture.internalGet(BaseCommand.java:287)
	at com.atlassian.bitbucket.scm.BaseCommand$CommandFuture.get(BaseCommand.java:251)
	at com.atlassian.bitbucket.scm.BaseCommand.call(BaseCommand.java:87)
	at com.atlassian.stash.internal.commit.DefaultCommitService.streamChanges(DefaultCommitService.java:223)
	at com.atlassian.plugin.util.ContextClassLoaderSettingInvocationHandler.invoke(ContextClassLoaderSettingInvocationHandler.java:26)
	at org.eclipse.gemini.blueprint.service.importer.support.internal.aop.ServiceInvoker.doInvoke(ServiceInvoker.java:56)
	at org.eclipse.gemini.blueprint.service.importer.support.internal.aop.ServiceInvoker.invoke(ServiceInvoker.java:60)
	at org.eclipse.gemini.blueprint.service.util.internal.aop.ServiceTCCLInterceptor.invokeUnprivileged(ServiceTCCLInterceptor.java:70)
	at org.eclipse.gemini.blueprint.service.util.internal.aop.ServiceTCCLInterceptor.invoke(ServiceTCCLInterceptor.java:53)
	at org.eclipse.gemini.blueprint.service.importer.support.LocalBundleContextAdvice.invoke(LocalBundleContextAdvice.java:57)
	at com.trimble.tekla.helpers.ChangesetService.GetChangedFiles(ChangesetService.java:60)
	at com.trimble.tekla.TeamcityTriggerHook.postUpdate(TeamcityTriggerHook.java:116)
	at com.atlassian.stash.internal.hook.repository.DefaultRepositoryHookService.postUpdate(DefaultRepositoryHookService.java:857)
	at com.atlassian.stash.internal.hook.repository.DefaultRepositoryHookService.lambda$doPostUpdate$7(DefaultRepositoryHookService.java:639)
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:133)
	at com.atlassian.stash.internal.hook.repository.DefaultRepositoryHookService.doPostUpdate(DefaultRepositoryHookService.java:623)
	at com.atlassian.stash.internal.hook.repository.DefaultRepositoryHookService.postUpdate(DefaultRepositoryHookService.java:412)
	at com.atlassian.stash.internal.hook.repository.CoreRefChangeEventToRepositoryHookAdapter.onRefsChanged(CoreRefChangeEventToRepositoryHookAdapter.java:55)
	at com.atlassian.event.internal.SingleParameterMethodListenerInvoker.invoke(SingleParameterMethodListenerInvoker.java:40)
	at com.atlassian.diagnostics.internal.platform.event.EventSystemMonitor.invokeMonitored(EventSystemMonitor.java:109)
	at com.atlassian.diagnostics.internal.platform.event.MonitoredListenerInvoker.invoke(MonitoredListenerInvoker.java:38)
	at com.atlassian.stash.internal.event.AsyncBatchingInvokersTransformer$AsyncInvokerBatch.invoke(AsyncBatchingInvokersTransformer.java:111)
	at com.atlassian.event.internal.AsynchronousAbleEventDispatcher$1$1.run(AsynchronousAbleEventDispatcher.java:38)
	at com.atlassian.sal.core.executor.ThreadLocalDelegateRunnable.run(ThreadLocalDelegateRunnable.java:34)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at com.atlassian.stash.internal.event.EventThreadFactory.lambda$createThread$0(EventThreadFactory.java:24)
	at java.lang.Thread.run(Thread.java:748)
	... 84 frames trimmed
```

**Comment by dzwicker** [comment]
```
"64451169-a2ee-4a82-9e4f-075c368315e6": {
        "regex": "refs/heads/v3/(.*)",
        "target": "eservice_backend_EServiceV3_SummarizeResults",
        "type": "build",
        "triggerOnEmptyBranches": true,
        "triggerOnPullRequest": false,
        "cancelRunningBuilds": false,
        "triggerInclusion": "",
        "triggerExclusion": "",
        "downStreamTriggerType": "build",
        "downStreamTriggerDescription": "",
        "downStreamTriggerTarget": ""
    }
```

**Comment by dzwicker** [comment]
```
object EService : GitVcsRoot({
    name = "eService"
    url = "ssh://git@xxxe/devb/xxxx.git"
    branchSpec = """
        +:refs/heads/(master)
        +:refs/heads/(feature/*)
        +:refs/heads/(bugfix/*)
        +:refs/heads/(hotfix/*)
        +:refs/heads/(release/*)
        +:refs/heads/(PR-*)
        +:refs/heads/(*)
        -:refs/heads/v3/(*)
    """.trimIndent()
    userForTags = "xxxx"
    authMethod = uploadedKey {
        userName = "teamcity"
        uploadedKey = "xxxxx"
        passphrase = "xxxx"
    }
})
```

**Comment by dzwicker** [comment]
Ok, will try the snapshot.

> can you try wiht this last snapshot?
> 
> [TeamCityTriggerHook-4.3.12.jar.zip](https://github.com/TrimbleSolutionsCorporation/TeamcityTriggerHook/files/2740825/TeamCityTriggerHook-4.3.12.jar.zip)
> 
> im not sure were that stacktrace is being sent actaully

**Comment by dzwicker** [comment]
The log with the 4.3.12 version is (stacktrace is not logged any more):
```
2019-01-10 14:15:54,500 INFO  [AtlassianEvent::thread-5] dzwicker @1PJIQIEx855x1926315x0 1vjnvrj 127.0.0.1 SSH - git-receive-pack '/devb/eservice.git' c.t.tekla.teamcity.TeamcityLogger [TeamcityTriggerHook ->] : postReceive: 0
[TeamcityTriggerHook ->] : postReceive: 0
2019-01-10 14:15:54,500 INFO  [AtlassianEvent::thread-5] dzwicker @1PJIQIEx855x1926315x0 1vjnvrj 127.0.0.1 SSH - git-receive-pack '/devb/eservice.git' c.t.tekla.teamcity.TeamcityLogger [TeamcityTriggerHook ->] : postReceive: 0
2019-01-10 14:15:54,501 DEBUG [ssh-scm-request-handler] dzwicker @1PJIQIEx855x1926315x0 1vjnvrj 127.0.0.1 SSH - git-receive-pack '/devb/eservice.git' c.a.bitbucket.scm.BaseCommand Executed /usr/bin/git receive-pack /var/atlassian/application-data/bitbucket/shared/data/repositories/64
2019-01-10 14:15:54,501 DEBUG [ssh-scm-request-handler] dzwicker @1PJIQIEx855x1926315x0 1vjnvrj 127.0.0.1 SSH - git-receive-pack '/devb/eservice.git' c.a.b.scm.ssh.SshCommandExitHandler /usr/bin/git receive-pack /var/atlassian/application-data/bitbucket/shared/data/repositories/64: (Exit code: 0)
2019-01-10 14:15:54,501 DEBUG [ref-sync-listener:thread-1] dzwicker @1PJIQIEx855x1926315x0 1vjnvrj 127.0.0.1 SSH - git-receive-pack '/devb/eservice.git' c.a.s.i.r.s.auto.AutoRefSyncListener DEVB/eservice[64]: Not updating status; synchronization is either not enabled or not available
2019-01-10 14:15:54,502 INFO  [AtlassianEvent::thread-5] dzwicker @1PJIQIEx855x1926315x0 1vjnvrj 127.0.0.1 SSH - git-receive-pack '/devb/eservice.git' c.t.tekla.teamcity.TeamcityLogger [TeamcityTriggerHook ->] : Trigger From Ref: refs/heads/v3/feature/empty3
[TeamcityTriggerHook ->] : Trigger From Ref: refs/heads/v3/feature/empty3
2019-01-10 14:15:54,502 INFO  [AtlassianEvent::thread-5] dzwicker @1PJIQIEx855x1926315x0 1vjnvrj 127.0.0.1 SSH - git-receive-pack '/devb/eservice.git' c.t.tekla.teamcity.TeamcityLogger [TeamcityTriggerHook ->] : Trigger From Ref: refs/heads/v3/feature/empty3
2019-01-10 14:15:54,530 DEBUG [AtlassianEvent::thread-5] dzwicker @1PJIQIEx855x1926315x0 1vjnvrj 127.0.0.1 SSH - git-receive-pack '/devb/eservice.git' c.a.bitbucket.scm.BaseCommand Executed /usr/bin/git branch --contains 9d286c5d62b3ad2f0c781de683e3b84b1a93b74f
2019-01-10 14:15:54,533 INFO  [AtlassianEvent::thread-5] dzwicker @1PJIQIEx855x1926315x0 1vjnvrj 127.0.0.1 SSH - git-receive-pack '/devb/eservice.git' c.t.tekla.teamcity.TeamcityLogger [TeamcityTriggerHook ->] : 20190110_141554 git branch: --contains 9d286c5d62b3ad2f0c781de683e3b84b1a93b74f
[TeamcityTriggerHook ->] : 20190110_141554 git branch: --contains 9d286c5d62b3ad2f0c781de683e3b84b1a93b74f
2019-01-10 14:15:54,533 INFO  [AtlassianEvent::thread-5] dzwicker @1PJIQIEx855x1926315x0 1vjnvrj 127.0.0.1 SSH - git-receive-pack '/devb/eservice.git' c.t.tekla.teamcity.TeamcityLogger [TeamcityTriggerHook ->] : 20190110_141554 git branch: --contains 9d286c5d62b3ad2f0c781de683e3b84b1a93b74f
2019-01-10 14:15:54,533 INFO  [AtlassianEvent::thread-5] dzwicker @1PJIQIEx855x1926315x0 1vjnvrj 127.0.0.1 SSH - git-receive-pack '/devb/eservice.git' c.t.tekla.teamcity.TeamcityLogger [TeamcityTriggerHook ->] : 20190110_141554 git result: '  v3/feature/empty3
'
[TeamcityTriggerHook ->] : 20190110_141554 git result: '  v3/feature/empty3
'
2019-01-10 14:15:54,534 INFO  [AtlassianEvent::thread-5] dzwicker @1PJIQIEx855x1926315x0 1vjnvrj 127.0.0.1 SSH - git-receive-pack '/devb/eservice.git' c.t.tekla.teamcity.TeamcityLogger [TeamcityTriggerHook ->] : 20190110_141554 git result: '  v3/feature/empty3
'
2019-01-10 14:15:54,547 DEBUG [commit-indexing:thread-1]  c.a.bitbucket.scm.BaseCommand Executed /usr/bin/git rev-list --format=%H%x02%P%x02%aN%x02%aE%x02%at%x02%cN%x02%cE%x02%ct%n%B%n%x03END%x04 --ignore-missing --no-min-parents --stdin --
2019-01-10 14:15:54,548 DEBUG [commit-indexing:thread-1]  c.a.s.i.i.DefaultCommitIndexingService [DEVB/eservice[64]] Scanning for deleted commits...
2019-01-10 14:15:54,556 DEBUG [AtlassianEvent::thread-5] dzwicker @1PJIQIEx855x1926315x0 1vjnvrj 127.0.0.1 SSH - git-receive-pack '/devb/eservice.git' c.a.bitbucket.scm.BaseCommand Executed /usr/bin/git diff-tree -C -r --format=%H 0000000000000000000000000000000000000000 9d286c5d62b3ad2f0c781de683e3b84b1a93b74f --
2019-01-10 14:15:54,566 INFO  [AtlassianEvent::thread-5] dzwicker @1PJIQIEx855x1926315x0 1vjnvrj 127.0.0.1 SSH - git-receive-pack '/devb/eservice.git' c.t.tekla.teamcity.TeamcityLogger [TeamcityTriggerHook ->] : No commit Exception: 0000000000000000000000000000000000000000
[TeamcityTriggerHook ->] : No commit Exception: 0000000000000000000000000000000000000000
2019-01-10 14:15:54,566 INFO  [AtlassianEvent::thread-5] dzwicker @1PJIQIEx855x1926315x0 1vjnvrj 127.0.0.1 SSH - git-receive-pack '/devb/eservice.git' c.t.tekla.teamcity.TeamcityLogger [TeamcityTriggerHook ->] : No commit Exception: 0000000000000000000000000000000000000000
2019-01-10 14:15:54,578 DEBUG [commit-indexing:thread-1]  c.a.bitbucket.scm.BaseCommand Executed /usr/bin/git rev-list --format=%H%x02%P%x02%aN%x02%aE%x02%at%x02%cN%x02%cE%x02%ct%n%B%n%x03END%x04 --ignore-missing --no-min-parents --stdin --
2019-01-10 14:15:54,612 DEBUG [commit-indexing:thread-1]  c.a.s.i.i.DefaultCommitIndexingService [DEVB/eservice[64]] Indexed 1 commits
2019-01-10 14:15:54,642 DEBUG [commit-graph:thread-1218]  c.a.bitbucket.scm.BaseCommand Executed /usr/bin/git rev-list --branches --ignore-missing --topo-order --parents --tags --
```

**Comment by jmecosta** [comment]
@dzwicker sorry for the wait. heres a new version, in order to enable debug you need to enable debug both in the diagnostic section and in the hook configuration for the repository. What im after is to check if the log is consistent with the version that im providing now. Im am getting quite a lot of issues, updating the plugin in our instance, basically even if uploading the plugin it never gets it. Ive contacted support and they finally mention this https://confluence.atlassian.com/upm/uninstalling-apps-273875709.html#Uninstallingapps-UninstallinganappbyremovingitsJARfile 

so if you could follow that procedure and then install 
[TeamCityTriggerHook-4.4.0.jar.zip](https://github.com/TrimbleSolutionsCorporation/TeamcityTriggerHook/files/2814333/TeamCityTriggerHook-4.4.0.jar.zip) this version.

**Comment by dzwicker** [comment]
Removed the old jar and restart the server. Uploaded the new version. Version in bitbucket plugin manager is 4.4.0

Here is the new log:
```
2019-02-06 14:18:28,009 INFO  [sshd-SshServer[489fabe1]-nio2-thread-3]  o.a.s.s.s.ServerUserAuthService Session git@/127.0.0.1:50472 authenticated
2019-02-06 14:18:28,073 DEBUG [AtlassianEvent::thread-5] dzwicker @195T2H4x858x553x0 1ovrcee 127.0.0.1 SSH - git-receive-pack '/devb/eservice.git' c.a.bitbucket.scm.BaseCommand Executed /usr/bin/git branch --contains 12eed444f0b80c918d4f83dbacfeae6d479e68d5
2019-02-06 14:18:28,074 INFO  [AtlassianEvent::thread-5] dzwicker @195T2H4x858x553x0 1ovrcee 127.0.0.1 SSH - git-receive-pack '/devb/eservice.git' c.t.tekla.teamcity.TeamcityLogger [TeamcityTriggerHook] : 20190206_141827 git branch: --contains 12eed444f0b80c918d4f83dbacfeae6d479e68d5
2019-02-06 14:18:28,074 INFO  [AtlassianEvent::thread-5] dzwicker @195T2H4x858x553x0 1ovrcee 127.0.0.1 SSH - git-receive-pack '/devb/eservice.git' c.t.tekla.teamcity.TeamcityLogger [TeamcityTriggerHook] : 20190206_141827 git result: '  v3/feature/devb-1431-product-sp-init
  v3/feature/empty-test
  v3/feature/gradle-5.2
  v3/feature/migrate-eid-stuff
* v3/master
'
2019-02-06 14:18:28,074 INFO  [AtlassianEvent::thread-5] dzwicker @195T2H4x858x553x0 1ovrcee 127.0.0.1 SSH - git-receive-pack '/devb/eservice.git' c.t.tekla.teamcity.TeamcityLogger [TeamcityTriggerHook] : 20190206_141827 Skip trigger no commits in branch: refs/heads/v3/feature/empty-test
2019-02-06 14:18:28,074 INFO  [AtlassianEvent::thread-5] dzwicker @195T2H4x858x553x0 1ovrcee 127.0.0.1 SSH - git-receive-pack '/devb/eservice.git' c.t.tekla.teamcity.TeamcityLogger [TeamcityTriggerHook] : 20190206_141827 From Hash: 0000000000000000000000000000000000000000
2019-02-06 14:18:28,074 INFO  [AtlassianEvent::thread-5] dzwicker @195T2H4x858x553x0 1ovrcee 127.0.0.1 SSH - git-receive-pack '/devb/eservice.git' c.t.tekla.teamcity.TeamcityLogger [TeamcityTriggerHook] : 20190206_141827 RefChange Type: ADD
2019-02-06 14:18:28,128 DEBUG [ssh-scm-request-handler] dzwicker @195T2H4x858x556x0 1pqwei6 127.0.0.1 SSH - git-upload-pack '/devb/eservice.git' c.a.bitbucket.scm.BaseCommand Executed /usr/bin/git upload-pack /var/atlassian/application-data/bitbucket/shared/data/repositories/64
2019-02-06 14:18:28,128 DEBUG [ssh-scm-request-handler] dzwicker @195T2H4x858x556x0 1pqwei6 127.0.0.1 SSH - git-upload-pack '/devb/eservice.git' c.a.b.scm.ssh.SshCommandExitHandler /usr/bin/git upload-pack /var/atlassian/application-data/bitbucket/shared/data/repositories/64: (Exit code: 0)
2019-02-06 14:18:28,129 DEBUG [ssh-scm-request-handler] dzwicker @195T2H4x858x556x0 1pqwei6 127.0.0.1 SSH - git-upload-pack '/devb/eservice.git' c.a.s.i.s.g.p.s.CachingSshUploadPack DEVB/eservice[64]: Completed git-upload-pack v1 [refs:bypass[23ms]]
2019-02-06 14:18:28,155 DEBUG [AtlassianEvent::thread-5] dzwicker @195T2H4x858x553x0 1ovrcee 127.0.0.1 SSH - git-receive-pack '/devb/eservice.git' c.a.bitbucket.scm.BaseCommand Executed /usr/bin/git diff-tree -C -r --format=%H 0000000000000000000000000000000000000000 12eed444f0b80c918d4f83dbacfeae6d479e68d5 --
2019-02-06 14:18:28,158 INFO  [AtlassianEvent::thread-5] dzwicker @195T2H4x858x553x0 1ovrcee 127.0.0.1 SSH - git-receive-pack '/devb/eservice.git' c.t.tekla.teamcity.TeamcityLogger [TeamcityTriggerHook] : No commit Exception: 0000000000000000000000000000000000000000
2019-02-06 14:18:28,161 DEBUG [AtlassianEvent::thread-1] dzwicker @195T2H4x858x553x0 1ovrcee 127.0.0.1 SSH - git-receive-pack '/devb/eservice.git' c.a.e.r.impl.RemoteEventListener Queueing RemoteEvent com.atlassian.stash.plugin.remote.event.StashBranchCreatedRemoteEvent@3444e411[branchName=v3/feature/empty-test,repositoryProject=DEVB,repositorySlug=eservice,committer=dzwicker,sourceId=<null>,sourceUrl=<null>]
2019-02-06 14:18:28,162 DEBUG [AtlassianEvent::thread-1] dzwicker @195T2H4x858x553x0 1ovrcee 127.0.0.1 SSH - git-receive-pack '/devb/eservice.git' c.a.e.r.impl.RemoteEventDispatcher RemoteEvent com.atlassian.stash.plugin.remote.event.StashBranchCreatedRemoteEvent@3444e411[branchName=v3/feature/empty-test,repositoryProject=DEVB,repositorySlug=eservice,committer=dzwicker,sourceId=<null>,sourceUrl=<null>] consumable by []
2019-02-06 14:18:28,164 DEBUG [AtlassianEvent::thread-1] dzwicker @195T2H4x858x553x0 1ovrcee 127.0.0.1 SSH - git-receive-pack '/devb/eservice.git' c.a.e.r.impl.RemoteEventListener Batch size not exceeded for com.atlassian.stash.plugin.remote.event.StashBranchCreatedRemoteEvent@3444e411[branchName=v3/feature/empty-test,repositoryProject=DEVB,repositorySlug=eservice,committer=dzwicker,sourceId=<null>,sourceUrl=<null>]
2019-02-06 14:18:28,182 DEBUG [commit-graph:thread-1]  c.a.bitbucket.scm.BaseCommand Executed /usr/bin/git rev-list --branches --ignore-missing --topo-order --parents --tags --






2019-02-06 14:18:42,050 DEBUG [http-nio-7990-exec-12] @195T2H4x858x557x0 172.16.192.221,127.0.0.1 "GET /rest/capabilities HTTP/1.1" c.a.b.i.c.s.CrowdSsoAuthenticationHandler Skipping Crowd SSO as it is not enabled
2019-02-06 14:18:42,051 DEBUG [http-nio-7990-exec-12] @195T2H4x858x557x0 172.16.192.221,127.0.0.1 "GET /rest/capabilities HTTP/1.1" c.a.s.i.i18n.PluginI18nService No values found in any valid locale for key ProviderManager.providerNotFound and locales [en_US, en, de_DE, de]
2019-02-06 14:18:42,052 DEBUG [http-nio-7990-exec-12] @195T2H4x858x557x0 172.16.192.221,127.0.0.1 "GET /rest/capabilities HTTP/1.1" c.a.b.i.c.s.CrowdSsoAuthenticationHandler Skipping Crowd SSO as it is not enabled
2019-02-06 14:18:42,053 DEBUG [http-nio-7990-exec-12] @195T2H4x858x557x0 172.16.192.221,127.0.0.1 "GET /rest/capabilities HTTP/1.1" c.a.s.i.i18n.PluginI18nService No values found in any valid locale for key ProviderManager.providerNotFound and locales [en_US, en, de_DE, de]
```

**Comment by jmecosta** [comment]
ok good,

Now i just need to know what is the stacktrace for the No commit Exception: 00000, not sure where that is comming from, can you 

[TeamCityTriggerHook-4.4.1.jar.zip](https://github.com/TrimbleSolutionsCorporation/TeamcityTriggerHook/files/2836727/TeamCityTriggerHook-4.4.1.jar.zip)

**Comment by solazs** [comment]
Hi, this is still an issue for us. We have a special case and I'd like to start a build for new empty branches only.
However, I get a no commit exception:
```
2019-12-09 12:48:42,966 INFO  [AtlassianEvent::thread-2] myuser *11Z906Tx768x1796238x6 1jqjd1b <ip-addr>,<ip-addr> "POST /rest/branch-utils/latest/projects/MY_PROJECT/repos/repo-id/branches HTTP/1.1" c.t.tekla.teamcity.TeamcityLogger [TeamcityTriggerHook] : postReceive: 0
2019-12-09 12:48:42,967 INFO  [AtlassianEvent::thread-2] myuser *11Z906Tx768x1796238x6 1jqjd1b <ip-addr>,<ip-addr> "POST /rest/branch-utils/latest/projects/MY_PROJECT/repos/repo-id/branches HTTP/1.1" c.t.tekla.teamcity.TeamcityLogger [TeamcityTriggerHook] : Trigger From Ref: refs/heads/hotfix/myuser-test3
2019-12-09 12:48:45,003 INFO  [AtlassianEvent::thread-2] myuser *11Z906Tx768x1796238x6 1jqjd1b <ip-addr>,<ip-addr> "POST /rest/branch-utils/latest/projects/MY_PROJECT/repos/repo-id/branches HTTP/1.1" c.t.tekla.teamcity.TeamcityLogger [TeamcityTriggerHook] : 20191209_124842 git branch: --contains be771b77bae23e547ff018f38798f2963dff4f4f
2019-12-09 12:48:45,003 INFO  [AtlassianEvent::thread-2] myuser *11Z906Tx768x1796238x6 1jqjd1b <ip-addr>,<ip-addr> "POST /rest/branch-utils/latest/projects/MY_PROJECT/repos/repo-id/branches HTTP/1.1" c.t.tekla.teamcity.TeamcityLogger [TeamcityTriggerHook] : 20191209_124842 git result: '* develop
  feature/update-repo-id-dependency-handling
  hotfix/myuser-test3
'
2019-12-09 12:48:45,004 INFO  [AtlassianEvent::thread-2] myuser *11Z906Tx768x1796238x6 1jqjd1b <ip-addr>,<ip-addr> "POST /rest/branch-utils/latest/projects/MY_PROJECT/repos/repo-id/branches HTTP/1.1" c.t.tekla.teamcity.TeamcityLogger [TeamcityTriggerHook] : 20191209_124842 Skip trigger no commits in branch: refs/heads/hotfix/myuser-test3
2019-12-09 12:48:45,004 INFO  [AtlassianEvent::thread-2] myuser *11Z906Tx768x1796238x6 1jqjd1b <ip-addr>,<ip-addr> "POST /rest/branch-utils/latest/projects/MY_PROJECT/repos/repo-id/branches HTTP/1.1" c.t.tekla.teamcity.TeamcityLogger [TeamcityTriggerHook] : 20191209_124842 From Hash: 0000000000000000000000000000000000000000
2019-12-09 12:48:45,004 INFO  [AtlassianEvent::thread-2] myuser *11Z906Tx768x1796238x6 1jqjd1b <ip-addr>,<ip-addr> "POST /rest/branch-utils/latest/projects/MY_PROJECT/repos/repo-id/branches HTTP/1.1" c.t.tekla.teamcity.TeamcityLogger [TeamcityTriggerHook] : 20191209_124842 RefChange Type: ADD
2019-12-09 12:48:45,018 INFO  [AtlassianEvent::thread-2] myuser *11Z906Tx768x1796238x6 1jqjd1b <ip-addr>,<ip-addr> "POST /rest/branch-utils/latest/projects/MY_PROJECT/repos/repo-id/branches HTTP/1.1" c.t.tekla.teamcity.TeamcityLogger [TeamcityTriggerHook] : No commit Exception: 0000000000000000000000000000000000000000 refs/heads/hotfix/myuser-test3
2019-12-09 12:48:45,018 INFO  [AtlassianEvent::thread-2] myuser *11Z906Tx768x1796238x6 1jqjd1b <ip-addr>,<ip-addr> "POST /rest/branch-utils/latest/projects/MY_PROJECT/repos/repo-id/branches HTTP/1.1" c.t.tekla.teamcity.TeamcityLogger [TeamcityTriggerHook] : Stacktrace: [Ljava.lang.StackTraceElement;@4ae82bf1 **refs/heads/hotfix/myuser-test3**
```

My guess is it is thrown here, when trying to calculate changes from the all-zero hash. https://github.com/TrimbleSolutionsCorporation/TeamcityTriggerHook/blob/57fe791fe81c73d8ed85ed0f818977f387085645/src/main/java/com/trimble/tekla/TeamcityTriggerHook.java#L112

Why calculate changes on an empty branch? The `ChangesetService.GetChangedFiles()` call could be skipped in case of an empty branch IMHO.

**Comment by jmecosta** [comment]
Do u have the option trigger on empty branch set to true?

**Comment by solazs** [comment]
@jmecosta Yes, I do have it set to true.

**Comment by solazs** [comment]
@jmecosta
The problem is, that wether ot not I have it set to true is not even checked until in the `TriggerBuild ` method.
The exception is thrown in `postUpdate` (I know this because of the log messages, since the stack trace is not logged properly)
Hence my asking for an `if` before calling `ChangesetService.GetChangedFiles()` in the `postUpdate` method in my previous comment.

**Comment by jmecosta** [comment]
Ok, can u make a pull request for that fix?

**Comment by solazs** [comment]
@jmecosta see #65 
I'll be available tomorrow if you need any changes.
